### ISSUE TITLE
Criar o projeto para o frontend do app

### ISSUE THREAD

**Issue by andreobueno** [santiagogustavo/fitness-app#4]
É preciso criar o projeto para o frontend do app. Neste caso, a tecnologia react Native será usada. 
Sendo assim, o projeto inicial deve ser criado, setado e commitado para este repositório no github

**Comment by santiagogustavo** [comment]
Os arquivos do projeto estão com os códigos de Front 😁 
Boa parte do trabalho está feita na branch `feature/splash-screen`, vou fazer o merge e começar a trabalhar com as issues e PRs
